use super::*;

#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct TileProps {
	pub terrain: Terrain,
	pub sprite: Sprite,
	pub model: Model,
	pub solid: u8,
}

pub static TILE_PROPS: [TileProps; 42] = [
	TileProps { terrain: Terrain::Blank, sprite: Sprite::Blank, model: Model::Empty, solid: SOLID_WALL },
	TileProps { terrain: Terrain::Floor, sprite: Sprite::Floor, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Wall, sprite: Sprite::Wall, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::Socket, sprite: Sprite::Floor, model: Model::Floor, solid: SOLID_WALL },
	TileProps { terrain: Terrain::BlueLock, sprite: Sprite::BlueDoor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::RedLock, sprite: Sprite::RedDoor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::GreenLock, sprite: Sprite::GreenDoor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::YellowLock, sprite: Sprite::YellowDoor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::Hint, sprite: Sprite::Hint, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Exit, sprite: Sprite::Exit1, model: Model::Portal, solid: 0 },
	TileProps { terrain: Terrain::Water, sprite: Sprite::Water, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Dirt, sprite: Sprite::Dirt, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Gravel, sprite: Sprite::Gravel, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Ice, sprite: Sprite::Ice, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::IceNW, sprite: Sprite::IceUL, model: Model::Floor, solid: PANEL_N | PANEL_W },
	TileProps { terrain: Terrain::IceNE, sprite: Sprite::IceUR, model: Model::Floor, solid: PANEL_N | PANEL_E },
	TileProps { terrain: Terrain::IceSW, sprite: Sprite::IceDL, model: Model::Floor, solid: PANEL_S | PANEL_W },
	TileProps { terrain: Terrain::IceSE, sprite: Sprite::IceDR, model: Model::Floor, solid: PANEL_S | PANEL_E },
	TileProps { terrain: Terrain::ForceN, sprite: Sprite::ForceUp, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ForceW, sprite: Sprite::ForceLeft, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ForceS, sprite: Sprite::ForceDown, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ForceE, sprite: Sprite::ForceRight, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ForceRandom, sprite: Sprite::ForceRandom, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::CloneMachine, sprite: Sprite::CloneMachine, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::ToggleFloor, sprite: Sprite::OnOffFloor, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ToggleWall, sprite: Sprite::OnOffWall, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::PanelN, sprite: Sprite::PanelNorth, model: Model::Floor, solid: PANEL_N },
	TileProps { terrain: Terrain::PanelW, sprite: Sprite::PanelWest, model: Model::Floor, solid: PANEL_W },
	TileProps { terrain: Terrain::PanelS, sprite: Sprite::PanelSouth, model: Model::Floor, solid: PANEL_S },
	TileProps { terrain: Terrain::PanelE, sprite: Sprite::PanelEast, model: Model::Floor, solid: PANEL_E },
	TileProps { terrain: Terrain::PanelSE, sprite: Sprite::PanelSE, model: Model::Floor, solid: PANEL_S | PANEL_E },
	TileProps { terrain: Terrain::HiddenWall, sprite: Sprite::Floor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::InvisWall, sprite: Sprite::Floor, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::BlueWall, sprite: Sprite::BlueWall, model: Model::Wall, solid: SOLID_WALL },
	TileProps { terrain: Terrain::BlueFake, sprite: Sprite::BlueWall, model: Model::Wall, solid: 0 },
	TileProps { terrain: Terrain::ButtonGreen, sprite: Sprite::GreenSwitch, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ButtonRed, sprite: Sprite::RedSwitch, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ButtonBrown, sprite: Sprite::BrownSwitch, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::ButtonBlue, sprite: Sprite::BlueSwitch, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::Teleport, sprite: Sprite::Teleport, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::BearTrap, sprite: Sprite::BearTrap, model: Model::Floor, solid: 0 },
	TileProps { terrain: Terrain::RecessedWall, sprite: Sprite::RecessedWall, model: Model::Wall, solid: 0 },
];
